version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_CLEANER_ENABLE: "true"
    ports:
      - "9092:9092"

  cassandra:
    image: cassandra:latest
    environment:
      CASSANDRA_CLUSTER_NAME: "database_cluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_LISTEN_ADDRESS: "cassandra"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra"
    ports:
      - "9042:9042" # Cassandra CQL port
  
  visualization:
    build: ./visualization/server/
    container_name: node-app
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - kafka
      - cassandra
  
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
  
  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_WEBUI_PORT: 8081
    ports:
      - "8000:8080"
      - "8081:8081"
    depends_on:
      - spark-master
  
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_WEBUI_PORT: 8081
    ports:
      - "8001:8080"
      - "8082:8081"
    depends_on:
      - spark-master
